### ISSUE TITLE
The demo site is not working

### ISSUE THREAD

**Issue by nalmeida** [SoftwareBrothers/admin-bro-example-app#16]
The Heroku example app is not working: https://admin-bro-example-app.herokuapp.com/admin

![image](https://user-images.githubusercontent.com/200209/98857532-f069c280-243d-11eb-9ca6-c1af51211571.png)

**Comment by SimonB407** [comment]
Yes, we are aware of this issue, we are migrating to other development solution. We will give you update as soon as this is fixed.

**Comment by dziraf** [comment]
URL: https://admin-bro-app.firebaseapp.com/admin
Credentials: admin@example.com / password

I'll leave the issue open until readme is updated

**Comment by nalmeida** [comment]
It is working! Closing this issue!

**Comment by rubiin** [comment]
> [admin@example.com](mailto:admin@example.com) /

credentials doesnt work
